version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server
  
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000