name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  CLIENT_IMAGE_NAME: ${{ github.repository_owner }}/mtsystem-client
  SERVER_IMAGE_NAME: ${{ github.repository_owner }}/mtsystem-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ${{ env.CLIENT_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.CLIENT_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.CLIENT_IMAGE_NAME }}:buildcache,mode=max

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: ${{ env.SERVER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.SERVER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.SERVER_IMAGE_NAME }}:buildcache,mode=max